local ASM_NOISE = {
    "MOV AX, BX",
    "XOR CX, CX",
    "PUSH BP",
    "POP BP",
    "ADD AX, 0x1F",
    "SUB DX, AX",
    "NOP",
    "CMP AX, BX",
    "JNE 0x004F",
    "JMP 0x00A1",
    "INC SI",
    "DEC DI",
    "MOV DS, AX",
    "MOV ES, BX",
    "INT 0x10",
    "INT 0x13",
    "INT 0x21",
    "LEA SI, [BP-04]",
    "LEA DI, [BP+08]",
    "SHL AX, 1",
    "SHR BX, 2",
    "ROL CX, 1",
    "ROR DX, 1",
    "AND AX, 0xFF",
    "OR BX, 0x80",
    "XCHG AX, DX",
    "TEST AX, AX",
    "JZ 0x0100",
    "JNZ 0x0104",
    "CALL 0x0FAB",
    "RET",
    "RET 0x04",
    "PUSHF",
    "POPF",
    "CLC",
    "STC",
    "CLI",
    "STI",
    "HLT",
    "WAIT",
    "MOV AL, [SI]",
    "MOV [DI], AL",
    "ADD SP, 2",
    "SUB SP, 2",
    "MOV BP, SP",
    "MOV SP, BP",
    "NEG AX",
    "NOT BX",
    "MUL CX",
    "DIV DX",
    "IMUL AX",
    "IDIV BX",
    "ADC AX, BX",
    "SBB CX, DX",
    "LODSB",
    "STOSB",
    "LODSW",
    "STOSW",
    "SCASB",
    "SCASW",
    "REP MOVSB",
    "REP MOVSW",
    "REP STOSB",
    "REP STOSW",
    "REPNE SCASB",
    "REPE CMPSB",
    "CMPSB",
    "CMPSW",
    "BOUND AX, [SI]",
    "ARPL AX, BX",
    "LDS SI, [BX]",
    "LES DI, [BX]",
    "ENTER 0x10, 0",
    "LEAVE",
    "PUSH AX",
    "PUSH BX",
    "PUSH CX",
    "PUSH DX",
    "POP AX",
    "POP BX",
    "POP CX",
    "POP DX",
    "MOV CR0, AX",
    "MOV AX, CR0",
    "LGDT [SI]",
    "LIDT [DI]",
    "SGDT [BP]",
    "SIDT [BP]",
    "SMSW AX",
    "LMSW AX",
    "IN AL, DX",
    "OUT DX, AL",
    "INSB",
    "OUTSB",
    "INSW",
    "OUTSW",
    "FADD ST, ST(1)",
    "FSUB ST, ST(2)",
    "FMUL ST, ST(3)",
    "FDIV ST, ST(4)",
    "FLD1",
    "FLDZ",
    "FSTP ST(0)",
    "FCOM ST(1)",
    "FWAIT",
    "FXCH ST(1)",
    "MOV EAX, EBX",
    "MOV EBX, ECX",
    "MOV ECX, EDX",
    "MOV EDX, EAX",
    "ADD EAX, 0xDEAD",
    "SUB EBX, 0xBEEF",
    "CMP ECX, 0x1337",
    "JGE 0xDEAD",
    "JL 0xBEEF",
    "JMP SHORT 0x42",
    "NOP ; padding",
    "NOP ; timing",
    "NOP ; align",
    "DB 0x90",
    "DB 0xCC",
    "DW 0xFFFF",
    "DD 0xDEADBEEF",
    "ALIGN 16",
    "SECTION .text",
    "SECTION .data",
    "SECTION .bss",
    "GLOBAL _start",
    "_start:",
    "MOV EAX, 1",
    "MOV EBX, 0",
    "INT 0x80",
}
