return {
    [1] = {
        ["freddy"] = 0,
        ["bonnie"] = 2,
        ["chica"] = 2,
        ["foxy"] = 0,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 0,
    },
    [2] = {
        ["freddy"] = 2,
        ["bonnie"] = 4,
        ["chica"] = 4,
        ["foxy"] = 4,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 0,
    },
    [3] = {
        ["freddy"] = 6,
        ["bonnie"] = 8,
        ["chica"] = 8,
        ["foxy"] = 6,
        ["sugar"] = 2,
        ["kitty"] = 2,
        ["puppet"] = 2,
    },
    [4] = {
        ["freddy"] = 8,
        ["bonnie"] = 12,
        ["chica"] = 12,
        ["foxy"] = 8,
        ["sugar"] = 6,
        ["kitty"] = 6,
        ["puppet"] = 8,
    },
    [5] = {
        ["freddy"] = 10,
        ["bonnie"] = 15,
        ["chica"] = 14,
        ["foxy"] = 10,
        ["sugar"] = 8,
        ["kitty"] = 8,
        ["puppet"] = 12,
    },
}