return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 25,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 246,
  backgroundcolor = { 60, 0, 90 },
  properties = {},
  tilesets = {
    {
      name = "map",
      firstgid = 1,
      class = "",
      tilewidth = 1072,
      tileheight = 1136,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "map.png",
      imagewidth = 1072,
      imageheight = 1136,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1072,
        height = 1136
      },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "map_img",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1136,
          width = 1072,
          height = 1136,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "areas",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["debug_color"] = "#ff4cc764"
      },
      objects = {
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 384,
          width = 400,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = true,
            ["zone_name"] = "kid_hall"
          }
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 576,
          width = 128,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "right_hall"
          }
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 576,
          width = 128,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "left_hall"
          }
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 960,
          width = 96,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "office_right_hall"
          }
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 960,
          width = 240,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "office"
          }
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 960,
          width = 96,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "office_left_hall"
          }
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 48,
          width = 240,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "bonnie_minigame"
          }
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 176,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "parts_and_service"
          }
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 0,
          width = 240,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "showstage"
          }
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 176,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "pirate_cove"
          }
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 240,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "dinning_area"
          }
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 192,
          width = 224,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "prize_corner"
          }
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 224,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "arcade"
          }
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 384,
          width = 224,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = false,
            ["zone_name"] = "storage"
          }
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 816,
          width = 464,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            ["scroll"] = true,
            ["zone_name"] = "front_office"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["debug_color"] = "#ffdfb22b"
      },
      objects = {
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 22.2424,
          y = 24.6667,
          width = 46.3939,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 77.6061,
          y = 24.7576,
          width = 46.3939,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 213.455,
          y = 212.636,
          width = 67.1818,
          height = 23.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 344.909,
          y = 210.273,
          width = 67.1818,
          height = 23.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224.125,
          y = 410.125,
          width = 17.5,
          height = 32.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224.75,
          y = 456.125,
          width = 17.5,
          height = 32.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224.125,
          y = 502.25,
          width = 17.5,
          height = 32.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 344.75,
          y = 412,
          width = 17.5,
          height = 32.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 376.625,
          y = 412.125,
          width = 17.5,
          height = 32.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 479,
          y = 452,
          width = 44.75,
          height = 60.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 611.25,
          y = 278.375,
          width = 37.625,
          height = 45.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 479.75,
          y = 267.625,
          width = 91.625,
          height = 11.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 625.25,
          y = 217.25,
          width = 21,
          height = 33.375,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496.25,
          y = 660.375,
          width = 45.875,
          height = 52.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 981.273,
          width = 26.9091,
          height = 30.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 374.182,
          y = 994.364,
          width = 66.7273,
          height = 23.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 981.818,
          width = 29.4545,
          height = 19.6364,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 112,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 16,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 0,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 160,
          width = 80,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 0,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 208,
          width = 48,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 336,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 352,
          width = 192,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 352,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 304,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 352,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 208,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 160,
          width = 272,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 192,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 80,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 208,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 400,
          width = 48,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 528,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 544,
          width = 80,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 544,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 400,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 544,
          width = 64,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 544,
          width = 64,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 400,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 464,
          width = 48,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 384,
          width = 368,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 400,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 496,
          width = 368,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 64,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 208,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 64,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 48,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 592,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 592,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 592,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 592,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 816,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 832,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 928,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 816,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 816,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 832,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 928,
          width = 336,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 928,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1104,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1104,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 976,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 976,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 976,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1072,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1120,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1072,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 976,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "action_zones",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["debug_color"] = "#ffff55ff"
      },
      objects = {
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 64,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "showstage"
          }
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "parts_and_service"
          }
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 160,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "dinning_area"
          }
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 192,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "showstage"
          }
        },
        {
          id = 194,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 256,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "dinning_area"
          }
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "pirate_cove"
          }
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 304,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "prize_corner"
          }
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 352,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "arcade"
          }
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 352,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "storage"
          }
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 304,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "dinning_area"
          }
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "prize_corner"
          }
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 416,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = true,
            ["on_enter_zone"] = "storage"
          }
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 416,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "kid_hall"
          }
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 544,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "left_hall"
          }
        },
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 496,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "arcade"
          }
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 496,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "storage"
          }
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "dinning_area"
          }
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 544,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "right_hall"
          }
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 576,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "arcade"
          }
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 784,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "front_office"
          }
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 784,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "front_office"
          }
        },
        {
          id = 213,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 576,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "storage"
          }
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 816,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "right_hall"
          }
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 816,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "left_hall"
          }
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 928,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "office_left_hall"
          }
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 928,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "down",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "office_right_hall"
          }
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 960,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "front_office"
          }
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1024,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "office"
          }
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 1024,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 18,
            ["locked"] = false,
            ["on_enter_zone"] = "office_right_hall"
          }
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1024,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "right",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "office_left_hall"
          }
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 1024,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "left",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "office"
          }
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 960,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["direction"] = "up",
            ["increment"] = 0,
            ["locked"] = false,
            ["on_enter_zone"] = "front_office"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "spawn_area",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["debug_color"] = "#ff4a1788"
      },
      objects = {
        {
          id = 182,
          name = "freddy",
          type = "",
          shape = "rectangle",
          x = 301.75,
          y = 37.25,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "bonnie",
          type = "",
          shape = "rectangle",
          x = 271.625,
          y = 20,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "chica",
          type = "",
          shape = "rectangle",
          x = 333.875,
          y = 20.25,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "foxy",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 289.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "night_guard",
          type = "",
          shape = "rectangle",
          x = 401.333,
          y = 1071.13,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "shadow_dug",
          type = "",
          shape = "rectangle",
          x = 405.667,
          y = 875.792,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 782,
          y = 96.4583,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "bonnie_child_minigame",
          type = "",
          shape = "rectangle",
          x = 862,
          y = 128.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 942,
          y = 96.4583,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 782,
          y = 128.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 942,
          y = 128.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 782,
          y = 160.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "child",
          type = "",
          shape = "rectangle",
          x = 942,
          y = 160.458,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
