return {
    [1] = {
        ["freddy"] = 0,
        ["bonnie"] = 0,
        ["chica"] = 0,
        ["foxy"] = 0,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 0,
    },
    [2] = {
        ["freddy"] = 0,
        ["bonnie"] = 3,
        ["chica"] = 2,
        ["foxy"] = 1,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 1,
    },
    [3] = {
        ["freddy"] = 1,
        ["bonnie"] = 7,
        ["chica"] = 7,
        ["foxy"] = 4,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 6,
    },
    [4] = {
        ["freddy"] = 3,
        ["bonnie"] = 8,
        ["chica"] = 8,
        ["foxy"] = 6,
        ["sugar"] = 3,
        ["kitty"] = 3,
        ["puppet"] = 7,
    },
    [5] = {
        ["freddy"] = 9,
        ["bonnie"] = 10,
        ["chica"] = 10,
        ["foxy"] = 10,
        ["sugar"] = 9,
        ["kitty"] = 10,
        ["puppet"] = 12,
    },
    [6] = {
        ["freddy"] = 15,
        ["bonnie"] = 14,
        ["chica"] = 13,
        ["foxy"] = 14,
        ["sugar"] = 16,
        ["kitty"] = 15,
        ["puppet"] = 15,
    },
}
