return {
    [1] = {
        ["freddy"] = 0,
        ["bonnie"] = 0,
        ["chica"] = 0,
        ["foxy"] = 0,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 0,
    },
    [2] = {
        ["freddy"] = 1,
        ["bonnie"] = 2,
        ["chica"] = 2,
        ["foxy"] = 2,
        ["sugar"] = 0,
        ["kitty"] = 0,
        ["puppet"] = 0,
    },
    [3] = {
        ["freddy"] = 2,
        ["bonnie"] = 8,
        ["chica"] = 8,
        ["foxy"] = 6,
        ["sugar"] = 2,
        ["kitty"] = 2,
        ["puppet"] = 2,
    },
    [4] = {
        ["freddy"] = 8,
        ["bonnie"] = 10,
        ["chica"] = 10,
        ["foxy"] = 8,
        ["sugar"] = 7,
        ["kitty"] = 6,
        ["puppet"] = 8,
    },
    [5] = {
        ["freddy"] = 10,
        ["bonnie"] = 15,
        ["chica"] = 14,
        ["foxy"] = 10,
        ["sugar"] = 8,
        ["kitty"] = 8,
        ["puppet"] = 12,
    },
    [6] = {
        ["freddy"] = 10,
        ["bonnie"] = 17,
        ["chica"] = 16,
        ["foxy"] = 12,
        ["sugar"] = 11,
        ["kitty"] = 11,
        ["puppet"] = 12,
    },
}
