return function()
    jit = require 'jit'
    http = require 'socket.http'
    utf8 = require 'utf8'
    bit = require 'bit'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    camera = require 'libraries.camera'
    collision = require 'libraries.collision'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    flux = require 'libraries.flux'
    json = require 'libraries.json'
    loveloader = require 'libraries.loveloader'
    lume = require 'libraries.lume'
    neuron = require 'libraries.neuron'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
end